// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file api/environment/environment.proto (package environment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, GetEnvironmentHealthResponse } from "./environment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service environment.v1.EnvironmentService
 */
export const EnvironmentService = {
  typeName: "environment.v1.EnvironmentService",
  methods: {
    /**
     * @generated from rpc environment.v1.EnvironmentService.GetEnvironmentHealth
     */
    getEnvironmentHealth: {
      name: "GetEnvironmentHealth",
      I: Empty,
      O: GetEnvironmentHealthResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

