// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/deployment/deployment.proto

package deploymentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	deployment "github.com/rschoonheim/docker-sphere/internal/api/deployment"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeploymentServiceName is the fully-qualified name of the DeploymentService service.
	DeploymentServiceName = "deployment.v1.DeploymentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeploymentServiceCreateDeploymentProcedure is the fully-qualified name of the DeploymentService's
	// CreateDeployment RPC.
	DeploymentServiceCreateDeploymentProcedure = "/deployment.v1.DeploymentService/CreateDeployment"
	// DeploymentServiceGetDeploymentProcedure is the fully-qualified name of the DeploymentService's
	// GetDeployment RPC.
	DeploymentServiceGetDeploymentProcedure = "/deployment.v1.DeploymentService/GetDeployment"
	// DeploymentServiceListDeploymentsProcedure is the fully-qualified name of the DeploymentService's
	// ListDeployments RPC.
	DeploymentServiceListDeploymentsProcedure = "/deployment.v1.DeploymentService/ListDeployments"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	deploymentServiceServiceDescriptor                = deployment.File_api_deployment_deployment_proto.Services().ByName("DeploymentService")
	deploymentServiceCreateDeploymentMethodDescriptor = deploymentServiceServiceDescriptor.Methods().ByName("CreateDeployment")
	deploymentServiceGetDeploymentMethodDescriptor    = deploymentServiceServiceDescriptor.Methods().ByName("GetDeployment")
	deploymentServiceListDeploymentsMethodDescriptor  = deploymentServiceServiceDescriptor.Methods().ByName("ListDeployments")
)

// DeploymentServiceClient is a client for the deployment.v1.DeploymentService service.
type DeploymentServiceClient interface {
	CreateDeployment(context.Context, *connect.Request[deployment.CreateDeploymentRequest]) (*connect.Response[deployment.CreateDeploymentResponse], error)
	GetDeployment(context.Context, *connect.Request[deployment.GetDeploymentRequest]) (*connect.Response[deployment.GetDeploymentResponse], error)
	ListDeployments(context.Context, *connect.Request[deployment.ListDeploymentsRequest]) (*connect.Response[deployment.ListDeploymentsResponse], error)
}

// NewDeploymentServiceClient constructs a client for the deployment.v1.DeploymentService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeploymentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeploymentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &deploymentServiceClient{
		createDeployment: connect.NewClient[deployment.CreateDeploymentRequest, deployment.CreateDeploymentResponse](
			httpClient,
			baseURL+DeploymentServiceCreateDeploymentProcedure,
			connect.WithSchema(deploymentServiceCreateDeploymentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDeployment: connect.NewClient[deployment.GetDeploymentRequest, deployment.GetDeploymentResponse](
			httpClient,
			baseURL+DeploymentServiceGetDeploymentProcedure,
			connect.WithSchema(deploymentServiceGetDeploymentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listDeployments: connect.NewClient[deployment.ListDeploymentsRequest, deployment.ListDeploymentsResponse](
			httpClient,
			baseURL+DeploymentServiceListDeploymentsProcedure,
			connect.WithSchema(deploymentServiceListDeploymentsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// deploymentServiceClient implements DeploymentServiceClient.
type deploymentServiceClient struct {
	createDeployment *connect.Client[deployment.CreateDeploymentRequest, deployment.CreateDeploymentResponse]
	getDeployment    *connect.Client[deployment.GetDeploymentRequest, deployment.GetDeploymentResponse]
	listDeployments  *connect.Client[deployment.ListDeploymentsRequest, deployment.ListDeploymentsResponse]
}

// CreateDeployment calls deployment.v1.DeploymentService.CreateDeployment.
func (c *deploymentServiceClient) CreateDeployment(ctx context.Context, req *connect.Request[deployment.CreateDeploymentRequest]) (*connect.Response[deployment.CreateDeploymentResponse], error) {
	return c.createDeployment.CallUnary(ctx, req)
}

// GetDeployment calls deployment.v1.DeploymentService.GetDeployment.
func (c *deploymentServiceClient) GetDeployment(ctx context.Context, req *connect.Request[deployment.GetDeploymentRequest]) (*connect.Response[deployment.GetDeploymentResponse], error) {
	return c.getDeployment.CallUnary(ctx, req)
}

// ListDeployments calls deployment.v1.DeploymentService.ListDeployments.
func (c *deploymentServiceClient) ListDeployments(ctx context.Context, req *connect.Request[deployment.ListDeploymentsRequest]) (*connect.Response[deployment.ListDeploymentsResponse], error) {
	return c.listDeployments.CallUnary(ctx, req)
}

// DeploymentServiceHandler is an implementation of the deployment.v1.DeploymentService service.
type DeploymentServiceHandler interface {
	CreateDeployment(context.Context, *connect.Request[deployment.CreateDeploymentRequest]) (*connect.Response[deployment.CreateDeploymentResponse], error)
	GetDeployment(context.Context, *connect.Request[deployment.GetDeploymentRequest]) (*connect.Response[deployment.GetDeploymentResponse], error)
	ListDeployments(context.Context, *connect.Request[deployment.ListDeploymentsRequest]) (*connect.Response[deployment.ListDeploymentsResponse], error)
}

// NewDeploymentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeploymentServiceHandler(svc DeploymentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deploymentServiceCreateDeploymentHandler := connect.NewUnaryHandler(
		DeploymentServiceCreateDeploymentProcedure,
		svc.CreateDeployment,
		connect.WithSchema(deploymentServiceCreateDeploymentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceGetDeploymentHandler := connect.NewUnaryHandler(
		DeploymentServiceGetDeploymentProcedure,
		svc.GetDeployment,
		connect.WithSchema(deploymentServiceGetDeploymentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceListDeploymentsHandler := connect.NewUnaryHandler(
		DeploymentServiceListDeploymentsProcedure,
		svc.ListDeployments,
		connect.WithSchema(deploymentServiceListDeploymentsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/deployment.v1.DeploymentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeploymentServiceCreateDeploymentProcedure:
			deploymentServiceCreateDeploymentHandler.ServeHTTP(w, r)
		case DeploymentServiceGetDeploymentProcedure:
			deploymentServiceGetDeploymentHandler.ServeHTTP(w, r)
		case DeploymentServiceListDeploymentsProcedure:
			deploymentServiceListDeploymentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeploymentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeploymentServiceHandler struct{}

func (UnimplementedDeploymentServiceHandler) CreateDeployment(context.Context, *connect.Request[deployment.CreateDeploymentRequest]) (*connect.Response[deployment.CreateDeploymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployment.v1.DeploymentService.CreateDeployment is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) GetDeployment(context.Context, *connect.Request[deployment.GetDeploymentRequest]) (*connect.Response[deployment.GetDeploymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployment.v1.DeploymentService.GetDeployment is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) ListDeployments(context.Context, *connect.Request[deployment.ListDeploymentsRequest]) (*connect.Response[deployment.ListDeploymentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployment.v1.DeploymentService.ListDeployments is not implemented"))
}
