/**
 * @fileoverview gRPC-Web generated client stub for environment.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: environment/environment.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as environment_environment_pb from '../environment/environment_pb';


export class EnvironmentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetEnvironmentHealth = new grpcWeb.MethodDescriptor(
    '/environment.v1.EnvironmentService/GetEnvironmentHealth',
    grpcWeb.MethodType.UNARY,
    environment_environment_pb.Empty,
    environment_environment_pb.GetEnvironmentHealthResponse,
    (request: environment_environment_pb.Empty) => {
      return request.serializeBinary();
    },
    environment_environment_pb.GetEnvironmentHealthResponse.deserializeBinary
  );

  getEnvironmentHealth(
    request: environment_environment_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<environment_environment_pb.GetEnvironmentHealthResponse>;

  getEnvironmentHealth(
    request: environment_environment_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: environment_environment_pb.GetEnvironmentHealthResponse) => void): grpcWeb.ClientReadableStream<environment_environment_pb.GetEnvironmentHealthResponse>;

  getEnvironmentHealth(
    request: environment_environment_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: environment_environment_pb.GetEnvironmentHealthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/environment.v1.EnvironmentService/GetEnvironmentHealth',
        request,
        metadata || {},
        this.methodDescriptorGetEnvironmentHealth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/environment.v1.EnvironmentService/GetEnvironmentHealth',
    request,
    metadata || {},
    this.methodDescriptorGetEnvironmentHealth);
  }

}

