// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file proto/gateway/docker/v1/containers.proto (package proto.gateway.docker.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListContainersRequest, ListContainersResponse } from "./containers_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.gateway.docker.v1.DockerService
 */
export const DockerService = {
  typeName: "proto.gateway.docker.v1.DockerService",
  methods: {
    /**
     * @generated from rpc proto.gateway.docker.v1.DockerService.ListContainers
     */
    listContainers: {
      name: "ListContainers",
      I: ListContainersRequest,
      O: ListContainersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

