// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file api/deployment/deployment.proto (package deployment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateDeploymentRequest, CreateDeploymentResponse, GetDeploymentRequest, GetDeploymentResponse, ListDeploymentsRequest, ListDeploymentsResponse } from "./deployment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service deployment.v1.DeploymentService
 */
export const DeploymentService = {
  typeName: "deployment.v1.DeploymentService",
  methods: {
    /**
     * @generated from rpc deployment.v1.DeploymentService.CreateDeployment
     */
    createDeployment: {
      name: "CreateDeployment",
      I: CreateDeploymentRequest,
      O: CreateDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetDeployment
     */
    getDeployment: {
      name: "GetDeployment",
      I: GetDeploymentRequest,
      O: GetDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.ListDeployments
     */
    listDeployments: {
      name: "ListDeployments",
      I: ListDeploymentsRequest,
      O: ListDeploymentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

